spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dangdang_check?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: duyeong0020@gmail.com
    password: ENC(8LyJGtUH0CHfZ9oO/exrRZT6oS58Z5nNCeeFjoMNkKQ=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection timeout: 5000
          timeout: 5000
          write timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false
solapi:
  api-key: ${SOLAPI_API_KEY}
  api-secret: ${SOLAPI_API_SECRET}
  base-url: https://api.coolsms.co.kr
  from-number: ${SOLAPI_FROM_NUMBER}
slack:
  webhook:
    url: https://hooks.slack.com/services/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
